/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KarticaRecepata: typeof import('./src/components/KarticaRecepata.vue')['default']
    KarticeFunkcionalnosti: typeof import('./src/components/KarticeFunkcionalnosti.vue')['default']
    Pretraga: typeof import('./src/components/Pretraga.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
