/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dodaj-recept': RouteRecordInfo<'/dodaj-recept', '/dodaj-recept', Record<never, never>, Record<never, never>>,
    '/paginacija': RouteRecordInfo<'/paginacija', '/paginacija', Record<never, never>, Record<never, never>>,
    '/recept': RouteRecordInfo<'/recept', '/recept', Record<never, never>, Record<never, never>>,
    '/recepti': RouteRecordInfo<'/recepti', '/recepti', Record<never, never>, Record<never, never>>,
    '/uredi-recept': RouteRecordInfo<'/uredi-recept', '/uredi-recept', Record<never, never>, Record<never, never>>,
  }
}
